version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app-net

  db:
    image: postgres:latest
    env_file:
      - .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

volumes:
  db-data:


networks:
  app-net:
